/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ContinentAdminPkg;

import Accounts.ContinentUA;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class ContinentAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form ContinentAdminWorkArea
     */
    JPanel mainJPanel;
    ContinentUA continentUA;
    public ContinentAdminWorkArea(JPanel mainJPanel,ContinentUA continentUA) {
        initComponents();
        this.mainJPanel = mainJPanel;
        this.continentUA = continentUA;
        welcomeLbl.setText("Welcome "+ continentUA.getAdmin().getP().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createCountryAdminBtn = new javax.swing.JButton();
        createPersonBtn = new javax.swing.JButton();
        viewAdminsBtn = new javax.swing.JButton();
        viewPersonBtn = new javax.swing.JButton();
        welcomeLbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createCountryAdminBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createCountryAdminBtn.setText("Create Country Admin");
        createCountryAdminBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        createCountryAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCountryAdminBtnActionPerformed(evt);
            }
        });
        add(createCountryAdminBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 170, -1));

        createPersonBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createPersonBtn.setText("Create Person");
        createPersonBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        createPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPersonBtnActionPerformed(evt);
            }
        });
        add(createPersonBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 123, 170, -1));

        viewAdminsBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewAdminsBtn.setText("View Admins");
        viewAdminsBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        viewAdminsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAdminsBtnActionPerformed(evt);
            }
        });
        add(viewAdminsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        viewPersonBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewPersonBtn.setText("View Persons");
        viewPersonBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        viewPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPersonBtnActionPerformed(evt);
            }
        });
        add(viewPersonBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, 50));

        welcomeLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLbl.setText("Welcome");
        add(welcomeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 35, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 112, 13, 335));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 71, 766, 15));
    }// </editor-fold>//GEN-END:initComponents

    private void createPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPersonBtnActionPerformed
        // TODO add your handling code here:
        CreatePersonContinentAdmin cp = new CreatePersonContinentAdmin(mainJPanel, continentUA.getAdmin().getPd());
        mainJPanel.add("Continental Admin Create Person", cp);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_createPersonBtnActionPerformed

    private void createCountryAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCountryAdminBtnActionPerformed
        // TODO add your handling code here:
        CreateCountryAdmin cp = new CreateCountryAdmin(mainJPanel, continentUA);
        mainJPanel.add("Continental Admin Create Country Admin", cp);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_createCountryAdminBtnActionPerformed

    private void viewPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPersonBtnActionPerformed
        // TODO add your handling code here:
        ViewPersonsContinentAdmin cp = new ViewPersonsContinentAdmin(mainJPanel, continentUA.getAdmin().getPd());
        mainJPanel.add("Continental Admin View Person", cp);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_viewPersonBtnActionPerformed

    private void viewAdminsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAdminsBtnActionPerformed
        // TODO add your handling code here:
        ViewAdminsContinentAdmin cp = new ViewAdminsContinentAdmin(mainJPanel, continentUA.getAdmin());
        mainJPanel.add("Continental Admin View Admin", cp);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_viewAdminsBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createCountryAdminBtn;
    private javax.swing.JButton createPersonBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton viewAdminsBtn;
    private javax.swing.JButton viewPersonBtn;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
