/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.CountryAdminPkg;

import Roles.CountryAdmin;
import Roles.StateAdmin;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class ViewAdminsCountryAdmin extends javax.swing.JPanel {

    /**
     * Creates new form ViewAdminsCountryAdmin
     */
    JPanel mainJPanel;
    CountryAdmin countryAdmin;
    public ViewAdminsCountryAdmin(JPanel mainJPanel,CountryAdmin countryAdmin) {
        initComponents();
        this.mainJPanel = mainJPanel;
        this.countryAdmin = countryAdmin;
        warningLbl.setVisible(false);
        popData();
    }

    void popData(){
        DefaultTableModel dtm = (DefaultTableModel)dataTable.getModel();
        dtm.setNumRows(0);
        for(StateAdmin admin : countryAdmin.getStateAdminList()){
            Object[] row = new Object[4];
            row[0] = admin.getP().getName();
            row[1] = admin.getUserAccount().getUserName();
            row[2] = admin.getP().getCity()+"," + admin.getP().getState();
            row[3] = admin.getState().getLocation().getValue();
            dtm.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dataTableSP = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        viewBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        warningLbl = new javax.swing.JLabel();
        refreshBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Admins");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "UserName", "Location", "Assign Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTableSP.setViewportView(dataTable);
        dataTable.getColumnModel().getColumn(0).setResizable(false);
        dataTable.getColumnModel().getColumn(1).setResizable(false);
        dataTable.getColumnModel().getColumn(2).setResizable(false);
        dataTable.getColumnModel().getColumn(3).setResizable(false);

        add(dataTableSP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 81, 702, 306));

        viewBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewBtn.setText("View/Update");
        viewBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        viewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewBtnActionPerformed(evt);
            }
        });
        add(viewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        backBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, -1, -1));

        warningLbl.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        warningLbl.setForeground(new java.awt.Color(255, 0, 0));
        warningLbl.setText("Please select Admin from Table.");
        add(warningLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, -1, -1));

        refreshBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        refreshBtn.setText("Refresh");
        refreshBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        add(refreshBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        mainJPanel.remove(this);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.previous(mainJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void viewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewBtnActionPerformed
        // TODO add your handling code here:
        warningLbl.setVisible(false);
        int selectedIndex = dataTable.getSelectedRow();
        if(selectedIndex>-1){
            UpdateAdminCountryAdmin upma = new UpdateAdminCountryAdmin(mainJPanel, countryAdmin.getStateAdminList().get(selectedIndex));
            mainJPanel.add("View State Admin Country Admin", upma);
            CardLayout layout = (CardLayout) mainJPanel.getLayout();
            layout.next(mainJPanel);
        }
        else{
            warningLbl.setVisible(true);
        }
    }//GEN-LAST:event_viewBtnActionPerformed

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        // TODO add your handling code here:
        popData();
    }//GEN-LAST:event_refreshBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTable dataTable;
    private javax.swing.JScrollPane dataTableSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton refreshBtn;
    private javax.swing.JButton viewBtn;
    private javax.swing.JLabel warningLbl;
    // End of variables declaration//GEN-END:variables
}
