/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.General;

import Accounts.ContinentUA;
import Accounts.MasterAccountsDirectory;
import Roles.CityAdmin;
import Roles.CountryAdmin;
import Roles.StateAdmin;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class EntityRequestParameter extends javax.swing.JPanel {

    /**
     * Creates new form EntityRequestParameter
     */
    JPanel mainJPanel;
    MasterAccountsDirectory mad;
    ContinentUA ca;
    CountryAdmin countryAdmin;
    StateAdmin stateAdmin;
    CityAdmin cityAdmin;
    public EntityRequestParameter(JPanel mainJPanel,MasterAccountsDirectory mad) {
        initComponents();
        this.mad = mad;
        this.mainJPanel = mainJPanel;
        continentContiBtn.setEnabled(true);
        countryContiBtn.setEnabled(false);
        stateBtn.setEnabled(false);
        cityBtn.setEnabled(false);
        setContinents();
    }

    void setContinents(){
        continentCB.removeAllItems();
        for(ContinentUA c : mad.getContinentAdmins())
        {
            continentCB.addItem(c.getAdmin().getContinent().getLocation().getValue());
        }
        continentContiBtn.setEnabled(true);
        countryContiBtn.setEnabled(false);
        stateBtn.setEnabled(false);
        cityBtn.setEnabled(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        continentCB = new javax.swing.JComboBox();
        continentContiBtn = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        countryCB = new javax.swing.JComboBox();
        countryContiBtn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        stateCB = new javax.swing.JComboBox();
        stateBtn = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        cityCB = new javax.swing.JComboBox();
        cityBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 153, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Continent", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        continentContiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FwdBtnImg.jpg"))); // NOI18N
        continentContiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                continentContiBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 29, Short.MAX_VALUE)
                .addComponent(continentCB, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(continentContiBtn)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(continentCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(continentContiBtn)
                .addContainerGap())
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 153, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select Country", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        countryContiBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FwdBtnImg.jpg"))); // NOI18N
        countryContiBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                countryContiBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(countryCB, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(countryContiBtn)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(countryCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(countryContiBtn)
                .addContainerGap())
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 90, -1, -1));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select State", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        stateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FwdBtnImg.jpg"))); // NOI18N
        stateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stateBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(stateCB, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stateBtn)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(stateCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(stateBtn)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 165, -1, -1));

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Select City", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        cityBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FwdBtnImg.jpg"))); // NOI18N
        cityBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cityBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addComponent(cityCB, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cityBtn)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(cityCB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(cityBtn)
                .addContainerGap())
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 226, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BackBtnImg.jpg"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void continentContiBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_continentContiBtnMouseClicked
        // TODO add your handling code here:
        ca = mad.getContinentAdmins().get(continentCB.getSelectedIndex());
        for(CountryAdmin c : ca.getAdmin().getCountryAdminList())
        {
            countryCB.addItem(c.getCountry().getLocation().getValue());
        }
        continentContiBtn.setEnabled(false);
        countryContiBtn.setEnabled(true);
        stateBtn.setEnabled(false);
        cityBtn.setEnabled(false);
    }//GEN-LAST:event_continentContiBtnMouseClicked

    private void countryContiBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_countryContiBtnMouseClicked
        // TODO add your handling code here:
        countryAdmin = ca.getAdmin().getCountryAdminList().get(countryCB.getSelectedIndex());
        
        for(StateAdmin c : countryAdmin.getStateAdminList())
        {
            stateCB.addItem(c.getState().getLocation().getValue());
        }
        continentContiBtn.setEnabled(false);
        countryContiBtn.setEnabled(false);
        stateBtn.setEnabled(true);
        cityBtn.setEnabled(false);
    }//GEN-LAST:event_countryContiBtnMouseClicked

    private void stateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stateBtnMouseClicked
        // TODO add your handling code here:
        stateAdmin = countryAdmin.getStateAdminList().get(stateCB.getSelectedIndex());
        
        for(CityAdmin c : stateAdmin.getCityAdminList())
        {
            cityCB.addItem(c.getCity().getLocation().getValue());
        }
        continentContiBtn.setEnabled(false);
        countryContiBtn.setEnabled(false);
        stateBtn.setEnabled(false);
        cityBtn.setEnabled(true);
    }//GEN-LAST:event_stateBtnMouseClicked

    private void cityBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cityBtnMouseClicked
        // TODO add your handling code here:
        cityAdmin = stateAdmin.getCityAdminList().get(cityCB.getSelectedIndex());
        RequestEntityRegister r = new RequestEntityRegister(mainJPanel, cityAdmin);
        mainJPanel.add("Guest New Entity Request.", r);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_cityBtnMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        mainJPanel.remove(this);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.previous(mainJPanel);
    }//GEN-LAST:event_jLabel1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cityBtn;
    private javax.swing.JComboBox cityCB;
    private javax.swing.JComboBox continentCB;
    private javax.swing.JLabel continentContiBtn;
    private javax.swing.JComboBox countryCB;
    private javax.swing.JLabel countryContiBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel stateBtn;
    private javax.swing.JComboBox stateCB;
    // End of variables declaration//GEN-END:variables
}
