/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.MainAdminPkg;

import HelperPkg.Helper;
import Roles.MasterAdminList;
import Roles.Person;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class CreateContinentAdmin extends javax.swing.JPanel {

    /**
     * Creates new form CreateContinentAdmin
     */
    JPanel mainJPanel;
    MasterAdminList masterAdminList;
    public CreateContinentAdmin(JPanel mainJPanel,MasterAdminList masterAdminList) {
        initComponents();
        this.mainJPanel = mainJPanel;
        this.masterAdminList = masterAdminList;
        warningLbl.setVisible(false);
        setData();
    }

    void setData(){
        DefaultTableModel dtm = (DefaultTableModel)dataTable.getModel();
        dtm.setNumRows(0);
        for(Person p : masterAdminList.getPd().getPersons()){
            Object[] row = new Object[4];
            row[0] = p.getName();
            row[1] = p.getCity();
            row[2] = p.getState();
            row[3] = p.getCountry();
            dtm.addRow(row);
        }  
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dataTableScrollPane = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        createBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        passwordTB = new javax.swing.JTextField();
        userNameTB = new javax.swing.JTextField();
        assignedContinentTB = new javax.swing.JTextField();
        warningLbl = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Continent Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 29, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Select Person");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 72, -1, -1));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "City", "State", "Country"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTableScrollPane.setViewportView(dataTable);
        dataTable.getColumnModel().getColumn(0).setResizable(false);
        dataTable.getColumnModel().getColumn(1).setResizable(false);
        dataTable.getColumnModel().getColumn(2).setResizable(false);

        add(dataTableScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 72, 267, 438));

        createBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createBtn.setText("Create Admin");
        createBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, -1, -1));

        backBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 420, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 60, 716, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("UserName");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 78, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Assigned City");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 157, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Password");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 114, -1, -1));

        passwordTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(passwordTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 114, 116, -1));

        userNameTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(userNameTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 72, 116, -1));

        assignedContinentTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(assignedContinentTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(596, 154, 116, -1));

        warningLbl.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        warningLbl.setForeground(new java.awt.Color(255, 0, 0));
        warningLbl.setText("Please fill in and select proper Values.");
        add(warningLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(471, 265, -1, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(415, 76, 13, 461));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        mainJPanel.remove(this);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.previous(mainJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    boolean validateFields(){
        HelperPkg.Helper h = new Helper();
        boolean flag =  h.isStringProper(userNameTB.getText(), passwordTB.getText(), assignedContinentTB.getText()); 
        
        return  flag;
    }
    void clearFields(){
        userNameTB.setText("");
        passwordTB.setText("");
        assignedContinentTB.setText("");
    }
    
    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        warningLbl.setVisible(false);
        int index = dataTable.getSelectedRow();
        if(validateFields() && index>-1){
            
            masterAdminList.createContinentAdmin(userNameTB.getText(), passwordTB.getText(), assignedContinentTB.getText(), index);
            clearFields();
            JOptionPane.showMessageDialog(this, "Continent Admin Created Successfully.");
        }
        else{
            warningLbl.setVisible(true);
        }
    }//GEN-LAST:event_createBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assignedContinentTB;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JTable dataTable;
    private javax.swing.JScrollPane dataTableScrollPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField passwordTB;
    private javax.swing.JTextField userNameTB;
    private javax.swing.JLabel warningLbl;
    // End of variables declaration//GEN-END:variables
}
