/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.MainAdminPkg;

import HelperPkg.Helper;
import Roles.Person;
import Roles.StateAdmin;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class UpdateAdminStateAdminMA extends javax.swing.JPanel {

    /**
     * Creates new form UpdateAdminStateAdminMA
     */
    JPanel mainJPanel;
    Person p;
    StateAdmin stateAdmin;
    public UpdateAdminStateAdminMA(JPanel mainJPanel,StateAdmin stateAdmin) {
        initComponents();
        this.mainJPanel = mainJPanel;
        this.stateAdmin = stateAdmin;
        warningLbl.setVisible(false);
       p = stateAdmin.getP();
       setData();
    }

    void setData(){
        nameTB.setText(p.getName());
        streetAddressTB.setText(p.getStreetAddress());
        cityTB.setText(p.getCity());
        stateTB.setText(p.getState());
        countryTB.setText(p.getCountry());
        zipTB.setText(p.getZipcode());
        phoneTB.setText(p.getPhone());
        faxTB.setText(p.getFax());
        emailTB.setText(p.getEmailAddress());
        userNameTB.setText(stateAdmin.getUserAccount().getUserName());
        passwordTB.setText(stateAdmin.getUserAccount().getPassword());
        assignedContinentTB.setText(stateAdmin.getState().getLocation().getValue());
        
    }
    boolean validateFields(){
        HelperPkg.Helper h = new Helper();
        boolean flag =  h.isStringProper(nameTB.getText(), streetAddressTB.getText(),cityTB.getText(), stateTB.getText(),countryTB.getText(),zipTB.getText(), phoneTB.getText(), faxTB.getText(), emailTB.getText(), userNameTB.getText(), passwordTB.getText(), assignedContinentTB.getText())
                && h.isProperLength(phoneTB.getText(), 10) && h.isProperLength(zipTB.getText(), 5); 
        
        return  flag;
    }
    void clearFields(){
        nameTB.setText("");
        streetAddressTB.setText("");
        cityTB.setText("");
        stateTB.setText("");
        countryTB.setText("");
        zipTB.setText("");
        phoneTB.setText("");
        faxTB.setText("");
        emailTB.setText("");
        userNameTB.setText("");
        passwordTB.setText("");
        assignedContinentTB.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createPersonTB = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        faxTB = new javax.swing.JTextField();
        streetAddressTB = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cityTB = new javax.swing.JTextField();
        emailTB = new javax.swing.JTextField();
        passwordTB = new javax.swing.JTextField();
        assignedContinentTB = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        countryTB = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        zipTB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nameTB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        stateTB = new javax.swing.JTextField();
        phoneTB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        warningLbl = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        userNameTB = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createPersonTB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createPersonTB.setText("Update");
        createPersonTB.setPreferredSize(new java.awt.Dimension(150, 50));
        createPersonTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPersonTBActionPerformed(evt);
            }
        });
        add(createPersonTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, -1, -1));

        backBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("State");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 208, -1, -1));

        faxTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(faxTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 370, 159, -1));

        streetAddressTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(streetAddressTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 125, 159, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Update Admin");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 28, -1, -1));

        cityTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(cityTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 165, 159, -1));

        emailTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(emailTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 405, 159, -1));

        passwordTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(passwordTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 123, 159, -1));

        assignedContinentTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(assignedContinentTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 163, 159, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 712, 10));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 81, 18, 440));

        countryTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(countryTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 245, 159, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Assigned City");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 166, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 408, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("UserName");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 87, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Password");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(434, 123, -1, -1));

        zipTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(zipTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 288, 159, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Street Address");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 128, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 84, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 337, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("City");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 165, -1, -1));

        nameTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(nameTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 81, 159, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ZipCode");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 291, -1, -1));

        stateTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(stateTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 205, 159, -1));

        phoneTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(phoneTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 330, 159, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fax");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 371, -1, -1));

        warningLbl.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        warningLbl.setForeground(new java.awt.Color(255, 0, 0));
        warningLbl.setText("Enter all Input Properly.");
        add(warningLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 409, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Country");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 248, -1, -1));

        userNameTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(userNameTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 81, 159, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        mainJPanel.remove(this);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.previous(mainJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void createPersonTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPersonTBActionPerformed
        // TODO add your handling code here:
        if(validateFields()){
            warningLbl.setVisible(false);
            p.updatePerson(nameTB.getText(), streetAddressTB.getText(), cityTB.getText(), stateTB.getText(), zipTB.getText(), phoneTB.getText(), faxTB.getText(), emailTB.getText(), countryTB.getText());
            stateAdmin.updateAdmin(p, userNameTB.getText(), passwordTB.getText(), assignedContinentTB.getText());
            clearFields();
            createPersonTB.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Admin Updated Successfully.");
        }
        else{
            warningLbl.setVisible(true);
        }  
    }//GEN-LAST:event_createPersonTBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField assignedContinentTB;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField cityTB;
    private javax.swing.JTextField countryTB;
    private javax.swing.JButton createPersonTB;
    private javax.swing.JTextField emailTB;
    private javax.swing.JTextField faxTB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField nameTB;
    private javax.swing.JTextField passwordTB;
    private javax.swing.JTextField phoneTB;
    private javax.swing.JTextField stateTB;
    private javax.swing.JTextField streetAddressTB;
    private javax.swing.JTextField userNameTB;
    private javax.swing.JLabel warningLbl;
    private javax.swing.JTextField zipTB;
    // End of variables declaration//GEN-END:variables
}
