/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.General.Reports.City;

import Complaints.CityComplaints;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class CitySelectReportType extends javax.swing.JPanel {

    /**
     * Creates new form CitySelectReportType
     */
    JPanel mainJPanel;
    CityComplaints cc;
    
    public CitySelectReportType(JPanel mainJPanel,CityComplaints cc) {
        initComponents();
        this.mainJPanel = mainJPanel;
        this.cc = cc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pieDegreeHarmBtn = new javax.swing.JButton();
        pieGenderBtn = new javax.swing.JButton();
        pieReportBtn = new javax.swing.JButton();
        pieEventPercenBtn = new javax.swing.JButton();
        pieRacebtn = new javax.swing.JButton();
        picIncidenceBtn = new javax.swing.JButton();
        pieAgeBtn = new javax.swing.JButton();
        barRacebtn = new javax.swing.JButton();
        barAgeBtn = new javax.swing.JButton();
        barGenderBtn = new javax.swing.JButton();
        barEventPercenBtn = new javax.swing.JButton();
        barDegreeHarmBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(0, 153, 204));

        pieDegreeHarmBtn.setText("Degree of Harm");
        pieDegreeHarmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieDegreeHarmBtnActionPerformed(evt);
            }
        });

        pieGenderBtn.setText("Gender by Event");
        pieGenderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieGenderBtnActionPerformed(evt);
            }
        });

        pieReportBtn.setText("Reporter");
        pieReportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieReportBtnActionPerformed(evt);
            }
        });

        pieEventPercenBtn.setText("Event Percentage");
        pieEventPercenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieEventPercenBtnActionPerformed(evt);
            }
        });

        pieRacebtn.setText("Race by Event");
        pieRacebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieRacebtnActionPerformed(evt);
            }
        });

        picIncidenceBtn.setText("Incidences");
        picIncidenceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picIncidenceBtnActionPerformed(evt);
            }
        });

        pieAgeBtn.setText("Age by Event");
        pieAgeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pieAgeBtnActionPerformed(evt);
            }
        });

        barRacebtn.setText("Race by Event");
        barRacebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barRacebtnActionPerformed(evt);
            }
        });

        barAgeBtn.setText("Age by Event");
        barAgeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barAgeBtnActionPerformed(evt);
            }
        });

        barGenderBtn.setText("Gender by Event");
        barGenderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barGenderBtnActionPerformed(evt);
            }
        });

        barEventPercenBtn.setText("Event Percentage");
        barEventPercenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barEventPercenBtnActionPerformed(evt);
            }
        });

        barDegreeHarmBtn.setText("Degree of Harm");
        barDegreeHarmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barDegreeHarmBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("View Report by:");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Pie Charts");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bar Charts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(220, 220, 220))
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pieGenderBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(barGenderBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pieEventPercenBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 265, Short.MAX_VALUE)
                        .addComponent(barEventPercenBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pieRacebtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(barRacebtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(pieAgeBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(barAgeBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pieReportBtn)
                            .addComponent(picIncidenceBtn))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pieDegreeHarmBtn)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(barDegreeHarmBtn))))
                .addGap(311, 311, 311))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 348, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(525, 525, 525)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pieDegreeHarmBtn)
                    .addComponent(barDegreeHarmBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barGenderBtn)
                    .addComponent(pieGenderBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barEventPercenBtn)
                    .addComponent(pieEventPercenBtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barRacebtn)
                    .addComponent(pieRacebtn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barAgeBtn)
                    .addComponent(pieAgeBtn))
                .addGap(26, 26, 26)
                .addComponent(picIncidenceBtn)
                .addGap(18, 18, 18)
                .addComponent(pieReportBtn)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(96, 96, 96)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(38, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void pieDegreeHarmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieDegreeHarmBtnActionPerformed
        // TODO add your handling code here:
        CityDegreeHarmPie s = new CityDegreeHarmPie(mainJPanel, cc);
        mainJPanel.add("Guest pieDegreeHarmBtnActionPerformed", s);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_pieDegreeHarmBtnActionPerformed

    private void pieGenderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieGenderBtnActionPerformed
        // TODO add your handling code here:
        CityEventGenderPie s = new CityEventGenderPie(mainJPanel, cc);
        mainJPanel.add("Guest pieGenderBtnActionPerformed.", s);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_pieGenderBtnActionPerformed

    private void pieEventPercenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieEventPercenBtnActionPerformed
        // TODO add your handling code here:
        CityEventPercentPie s = new CityEventPercentPie(mainJPanel, cc);
        mainJPanel.add("Guest pieEventPercenBtnActionPerformed.", s);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_pieEventPercenBtnActionPerformed

    private void pieRacebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieRacebtnActionPerformed
        // TODO add your handling code here:
        CityEventRacePie s = new CityEventRacePie(mainJPanel, cc);
        mainJPanel.add("Guest pieRacebtnActionPerformed.", s);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_pieRacebtnActionPerformed

    private void pieAgeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieAgeBtnActionPerformed
        // TODO add your handling code here:
       CityIncidentbyAgePie s = new CityIncidentbyAgePie(mainJPanel, cc);
        mainJPanel.add("Guest pieAgeBtnActionPerformed.", s);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_pieAgeBtnActionPerformed

    private void picIncidenceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picIncidenceBtnActionPerformed
        // TODO add your handling code here:
        CityIncidentPercentPie s = new CityIncidentPercentPie(mainJPanel, cc);
        mainJPanel.add("Guest picIncidenceBtnActionPerformed.", s);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_picIncidenceBtnActionPerformed

    private void pieReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pieReportBtnActionPerformed
        // TODO add your handling code here:
        CityReporterPie s = new CityReporterPie(mainJPanel, cc);
        mainJPanel.add("Guest pieReportBtnActionPerformed.", s);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_pieReportBtnActionPerformed

    private void barDegreeHarmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barDegreeHarmBtnActionPerformed
        // TODO add your handling code here:
        CityDegreeHarmBar s = new CityDegreeHarmBar(mainJPanel, cc);
        mainJPanel.add("Guest barDegreeHarmBtnActionPerformed.", s);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_barDegreeHarmBtnActionPerformed

    private void barGenderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barGenderBtnActionPerformed
        // TODO add your handling code here:
       CityEventGenderBar s  = new CityEventGenderBar(mainJPanel, cc);
        mainJPanel.add("Guest barGenderBtnActionPerformed.", s);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_barGenderBtnActionPerformed

    private void barEventPercenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barEventPercenBtnActionPerformed
        // TODO add your handling code here:
        CityEventPercentBar s = new CityEventPercentBar(mainJPanel, cc);
        mainJPanel.add("Guest barEventPercenBtnActionPerformed", s);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_barEventPercenBtnActionPerformed

    private void barRacebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barRacebtnActionPerformed
        // TODO add your handling code here:
        CityEventRaceBar s = new CityEventRaceBar(mainJPanel, cc);
        mainJPanel.add("Guest barRacebtnActionPerformed.", s);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_barRacebtnActionPerformed

    private void barAgeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barAgeBtnActionPerformed
        // TODO add your handling code here:
        CityIncidentbyAgeBar s = new CityIncidentbyAgeBar(mainJPanel, cc);
        mainJPanel.add("Guest barAgeBtnActionPerformed.", s);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_barAgeBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mainJPanel.remove(this);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.previous(mainJPanel);
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton barAgeBtn;
    private javax.swing.JButton barDegreeHarmBtn;
    private javax.swing.JButton barEventPercenBtn;
    private javax.swing.JButton barGenderBtn;
    private javax.swing.JButton barRacebtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton picIncidenceBtn;
    private javax.swing.JButton pieAgeBtn;
    private javax.swing.JButton pieDegreeHarmBtn;
    private javax.swing.JButton pieEventPercenBtn;
    private javax.swing.JButton pieGenderBtn;
    private javax.swing.JButton pieRacebtn;
    private javax.swing.JButton pieReportBtn;
    // End of variables declaration//GEN-END:variables
}
