/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.CityAdmin.ViewNewComplainsPkg;

import Complaints.Category.BasicComplaint;
import HelperPkg.Helper;
import Roles.CityAdmin;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class BasicComplaintJPanel extends javax.swing.JPanel {

    /**
     * Creates new form BasicComplaintJPanel
     */
    JPanel mainJPanel;
    CityAdmin cityAdmin;
    BasicComplaint bc;
    String type;
    int index;
    public BasicComplaintJPanel(JPanel mainJPanel,CityAdmin cityAdmin, String type,int index) {
        initComponents();
        this.mainJPanel = mainJPanel;
        this.cityAdmin = cityAdmin;
        this.type = type;
        this.index = index;
        setBC();
        setValues();
        warningLbl.setVisible(false);
    }

    
    void setValues(){
        reportDateTb.setText(bc.getReportDate());
        discDateCB.setText(bc.getDicoveryDate());
        DiscTimeTB.setText(bc.getDiscoveryTime());
        descTB.setText(bc.getDescription());
        HelperPkg.Helper h = new Helper();
        categoryCB.setSelectedIndex(h.getIndexForComboBox(bc.getCategory(), categoryCB));
        
        eventCB.setSelectedIndex(h.getIndexForComboBox(bc.getEventReported(), eventCB));
        ageCB.setSelectedIndex(h.getIndexForComboBox(bc.getPatientAge(), ageCB));
        locCB.setSelectedIndex(h.getIndexForComboBox(bc.getLocation(), locCB));
        genderCB.setSelectedIndex(h.getIndexForComboBox(bc.getGender(), genderCB));
        raceCB.setSelectedIndex(h.getIndexForComboBox(bc.getRace(), raceCB));
        degreeCb.setSelectedIndex(h.getIndexForComboBox(bc.getDegree(), degreeCb));
        durationCB.setSelectedIndex(h.getIndexForComboBox(bc.getDuration(), durationCB));
        reporterCB.setSelectedIndex(h.getIndexForComboBox(bc.getReporter(), reporterCB));
    }
    void setBC(){
        switch(type){
            case "Blood or Blood Product":
                bc = cityAdmin.getComplaint().getBloodEvents().get(index).getBc();
                break;
            case "Device or Medical/Surgical Supply":
                bc = cityAdmin.getComplaint().getDeviceSurguryEvents().get(index).getBc();
                break;
            case "Fall":
                bc = cityAdmin.getComplaint().getFallEvents().get(index).getBc();
                break;
            case "Healthcare-associated Infection":
                bc = cityAdmin.getComplaint().getInfectionEvents().get(index).getBc();
                break;
            case "Medication or Other Substance":
                bc = cityAdmin.getComplaint().getMedicationEvents().get(index).getBc();
                break;
            case "Perinatal":
                bc = cityAdmin.getComplaint().getPeriNatalEvents().get(index).getBc();
                break;
            case "Pressure Ulcer":
                bc = cityAdmin.getComplaint().getPressureUlcerEvents().get(index).getBc();
                break;
            case "Surgery or Anesthesia":
                bc = cityAdmin.getComplaint().getSurgeryEvents().get(index).getBc();
                break;
            case "Venous Thromboembolism":
                bc = cityAdmin.getComplaint().getVenousEvents().get(index).getBc();
                break;
             
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        descTB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        warningLbl = new javax.swing.JLabel();
        reportDateTb = new javax.swing.JTextField();
        DiscTimeTB = new javax.swing.JTextField();
        discDateCB = new javax.swing.JTextField();
        eventCB = new javax.swing.JComboBox();
        genderCB = new javax.swing.JComboBox();
        degreeCb = new javax.swing.JComboBox();
        reporterCB = new javax.swing.JComboBox();
        durationCB = new javax.swing.JComboBox();
        categoryCB = new javax.swing.JComboBox();
        ageCB = new javax.swing.JComboBox();
        locCB = new javax.swing.JComboBox();
        raceCB = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Next");
        jButton1.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 490, -1, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Basic Description");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 27, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Report Date");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 78, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Event Reported");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 112, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Discovery Date");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 153, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Discovery Time");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 192, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Description");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 271, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Location");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 192, -1, -1));

        descTB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        add(descTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 268, 600, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Category");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(603, 114, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Patient Age range");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 153, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Gender");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 231, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Race");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 309, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Degree of harm");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 349, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Duration of harm to the patient  ");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 387, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Reporter information ");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 427, -1, -1));

        warningLbl.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        warningLbl.setForeground(new java.awt.Color(255, 0, 0));
        warningLbl.setText("Please enter description.");
        add(warningLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        reportDateTb.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        add(reportDateTb, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 73, 107, -1));

        DiscTimeTB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        add(DiscTimeTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 190, 107, -1));

        discDateCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        add(discDateCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 151, 107, -1));

        eventCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        eventCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Incident", "Near Miss", "Unsafe Condition" }));
        add(eventCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 112, -1, -1));

        genderCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        genderCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male ", "Female" }));
        add(genderCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 229, -1, -1));

        degreeCb.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        degreeCb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Death", "Severe harm", "Moderate harm", "Mild harm", "No harm", " " }));
        add(degreeCb, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 346, -1, -1));

        reporterCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        reporterCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Doctor, dentist ", "Nurse, nurse practitioner, physician assistant", "Pharmacist, pharmacy technician (including student) ", "Allied health professionals ", "Healthcare worker", "Emergency service personnel", "Patient, family member, volunteer, caregiver, or homecare assistant" }));
        add(reporterCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 424, -1, -1));

        durationCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        durationCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Permanent", "Temporary" }));
        add(durationCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 385, -1, -1));

        categoryCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        categoryCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Blood or Blood Product", "Device or Medical/Surgical Supply", "Fall", "Healthcare-associated Infection", "Medication or Other Substance", "Perinatal", "Pressure Ulcer", "Surgery or Anesthesia", "Venous Thromboembolism" }));
        categoryCB.setEnabled(false);
        add(categoryCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(709, 112, -1, -1));

        ageCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        ageCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Neonate (0-28 days) ", "Infant (>28 days <1 year) ", "Child (1-12 years) ", "Adolescent (13-17 years) ", "Adult (18-64 years) ", "Mature adult (65-74 years) ", "Older adult (75-84 years) ", "Aged adult (85+ years) " }));
        add(ageCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 151, -1, -1));

        locCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        locCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inpatient general care area (e.g., medical/surgical unit) ", "Special care area (e.g., ICU, CCU, NICU) ", "Labor and delivery ", "Operating room or procedure area", "Radiology/imaging department, including onsite mobile units ", "Pharmacy ", "Laboratory, including pathology department and blood bank ", "Emergency department ", "Other area within the facility ", "Outpatient care area ", "Outside area (i.e., grounds of the facility)", "Other" }));
        add(locCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 190, -1, -1));

        raceCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        raceCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "American Indian or Alaska Native ", "Asian ", "Black or African American ", "Native Hawaiian or Other Pacific Islander ", "White ", "More than one race " }));
        add(raceCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 307, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        mainJPanel.remove(this);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.previous(mainJPanel);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        warningLbl.setVisible(false);
        Helper h = new Helper();
        boolean flag = h.isStringProper(descTB.getText(), reportDateTb.getText(), discDateCB.getText(),DiscTimeTB.getText());
        if(flag){
            bc.setReportDate(reportDateTb.getText());
            bc.setCategory(categoryCB.getSelectedItem().toString().trim());
            bc.setEventReported(eventCB.getSelectedItem().toString());
            bc.setDicoveryDate(discDateCB.getText());
            bc.setDiscoveryTime(DiscTimeTB.getText());
            bc.setPatientAge(ageCB.getSelectedItem().toString());
            bc.setDescription(descTB.getText());
            bc.setLocation(locCB.getSelectedItem().toString());
            bc.setGender(genderCB.getSelectedItem().toString());
            bc.setRace(raceCB.getSelectedItem().toString());
            bc.setDegree(degreeCb.getSelectedItem().toString());
            bc.setDuration(durationCB.getSelectedItem().toString());
            bc.setReporter(reporterCB.getSelectedItem().toString());
            switch(bc.getCategory()){
                case "Blood or Blood Product":
                    BloodEventJPanel evnt = new BloodEventJPanel(mainJPanel, cityAdmin, cityAdmin.getComplaint().getBloodEvents().get(index));
                    mainJPanel.add("City Admin View Blood Event Request", evnt);
                    CardLayout layout = (CardLayout) mainJPanel.getLayout();
                    layout.next(mainJPanel);
                    break;
                case "Device or Medical/Surgical Supply":
                    DevicesEventJPanel evnt1 = new DevicesEventJPanel(mainJPanel, cityAdmin, cityAdmin.getComplaint().getDeviceSurguryEvents().get(index));
                    mainJPanel.add("City Admin View Device Event Request", evnt1);
                    CardLayout layout1 = (CardLayout) mainJPanel.getLayout();
                    layout1.next(mainJPanel);
                    break;
                case "Fall":
                    FallEventJPanel evnt2 = new FallEventJPanel(mainJPanel, cityAdmin, cityAdmin.getComplaint().getFallEvents().get(index));
                    mainJPanel.add("City Admin View Fall Event Request", evnt2);
                    CardLayout layout2 = (CardLayout) mainJPanel.getLayout();
                    layout2.next(mainJPanel);
                    break;
                case "Healthcare-associated Infection":
                    HealthInfectionEventJPanel evnt3 = new HealthInfectionEventJPanel(mainJPanel, cityAdmin, cityAdmin.getComplaint().getInfectionEvents().get(index));
                    mainJPanel.add("City Admin View Infection Event Request", evnt3);
                    CardLayout layout3 = (CardLayout) mainJPanel.getLayout();
                    layout3.next(mainJPanel);
                    break;
                    
                case "Medication or Other Substance":
                    MedicalEventJPanel evnt4 = new MedicalEventJPanel(mainJPanel, cityAdmin, cityAdmin.getComplaint().getMedicationEvents().get(index));
                    mainJPanel.add("City Admin View Medication Event Request", evnt4);
                    CardLayout layout4 = (CardLayout) mainJPanel.getLayout();
                    layout4.next(mainJPanel);
                    break;
                    
                case "Perinatal":
                    PerinatalEventJPanel evnt5 = new PerinatalEventJPanel(mainJPanel, cityAdmin, cityAdmin.getComplaint().getPeriNatalEvents().get(index));
                    mainJPanel.add("City Admin View Perinatal Event Request", evnt5);
                    CardLayout layout5 = (CardLayout) mainJPanel.getLayout();
                    layout5.next(mainJPanel);
                    break;
                    
                case "Pressure Ulcer":
                    PressureUlcerEventJPanel evnt6 = new PressureUlcerEventJPanel(mainJPanel, cityAdmin, cityAdmin.getComplaint().getPressureUlcerEvents().get(index));
                    mainJPanel.add("City Admin View Pressure Event Request", evnt6);
                    CardLayout layout6 = (CardLayout) mainJPanel.getLayout();
                    layout6.next(mainJPanel);
                    break;
                    
                case "Surgery or Anesthesia":
                    SurgeryEventJPanel evnt7 = new SurgeryEventJPanel(mainJPanel, cityAdmin, cityAdmin.getComplaint().getSurgeryEvents().get(index));
                    mainJPanel.add("City Admin View Surgery Event Request", evnt7);
                    CardLayout layout7 = (CardLayout) mainJPanel.getLayout();
                    layout7.next(mainJPanel);
                    break;
                   
                case "Venous Thromboembolism":
                    VenousEventJPanel evnt8 = new VenousEventJPanel(mainJPanel, cityAdmin, cityAdmin.getComplaint().getVenousEvents().get(index));
                    mainJPanel.add("City Admin View Blood Event Request", evnt8);
                    CardLayout layout8 = (CardLayout) mainJPanel.getLayout();
                    layout8.next(mainJPanel);
                    break;
                    
                    
            }
        }
        else{
            warningLbl.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DiscTimeTB;
    private javax.swing.JComboBox ageCB;
    private javax.swing.JComboBox categoryCB;
    private javax.swing.JComboBox degreeCb;
    private javax.swing.JTextField descTB;
    private javax.swing.JTextField discDateCB;
    private javax.swing.JComboBox durationCB;
    private javax.swing.JComboBox eventCB;
    private javax.swing.JComboBox genderCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox locCB;
    private javax.swing.JComboBox raceCB;
    private javax.swing.JTextField reportDateTb;
    private javax.swing.JComboBox reporterCB;
    private javax.swing.JLabel warningLbl;
    // End of variables declaration//GEN-END:variables
}
