/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.CityAdmin.ViewNewComplainsPkg;

import View.ComplaintsPkg.*;
import Complaints.Category.BasicComplaint;
import Complaints.Category.FallEvent;
import HelperPkg.Helper;
import Roles.CityAdmin;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class FallEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form FallEventJPanel
     */
    JPanel mainJPanel;
    CityAdmin cityAdmin;
    FallEvent fe;
    public FallEventJPanel(JPanel mainJPanel,CityAdmin cityAdmin,FallEvent fe) {
        initComponents();
        this.mainJPanel = mainJPanel;
        this.cityAdmin = cityAdmin;
        this.fe = fe;
        setValues();
        
    }

    public void setValues(){
        HelperPkg.Helper h = new Helper();
        assistedCB.setSelectedIndex(h.getIndexForComboBox(fe.getIsAssisted(), assistedCB));
        observedCB.setSelectedIndex(h.getIndexForComboBox(fe.getIsObserved(), observedCB));
        injuryCB.setSelectedIndex(h.getIndexForComboBox(fe.getIsInjury(), injuryCB));
        priorCB.setSelectedIndex(h.getIndexForComboBox(fe.getPriorWork(), priorCB));
        assessCB.setSelectedIndex(h.getIndexForComboBox(fe.getIsRiskAssessed(), assessCB));
        factorCB.setSelectedIndex(h.getIndexForComboBox(fe.getRiskFactor(), factorCB));
        preventCB.setSelectedIndex(h.getIndexForComboBox(fe.getPreventive(), preventCB));
        medicationCB.setSelectedIndex(h.getIndexForComboBox(fe.getOnMedication(), medicationCB));
        contributeCB.setSelectedIndex(h.getIndexForComboBox(fe.getContribute(), contributeCB));
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        approveBtn1 = new javax.swing.JButton();
        factorCB = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        preventCB = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        medicationCB = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        assessCB = new javax.swing.JComboBox();
        contributeCB = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        priorCB = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        injuryCB = new javax.swing.JComboBox();
        assistedCB = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        observedCB = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        approveBtn1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        approveBtn1.setText("Update");
        approveBtn1.setPreferredSize(new java.awt.Dimension(150, 50));
        approveBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtn1ActionPerformed(evt);
            }
        });
        add(approveBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, -1, -1));

        factorCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        factorCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "History of previous fall ", "Prosthesis or specialty/prescription shoe ", "Sensory impairment (vision, hearing, balance, etc.) ", "None ", "Unknown" }));
        add(factorCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 282, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("At the time of the fall, were any of the following risk factors present?");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 284, -1, -1));

        preventCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        preventCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Assistive device  ", "Bed or chair alarm ", "Bed in low position ", "Call light/personal items within reach ", "Change in medication (e.g., timing or dosing of current medication) ", "Non-slip floor mats ", "Hip and/or joint protectors ", "Non-slip footwear ", "Patient and family education ", "Patient sitting close to the nurses’ station ", "Physical/occupational therapy, includes exercise or mobility program ", "Sitter ", "Supplemental environmental or area lighting", "Toileting regimen ", "Visible identification of patient as being at risk for fall ", "None ", "Unknown" }));
        add(preventCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 321, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Which of the following were in place and being used to prevent falls for this patient?");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 323, -1, -1));

        medicationCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        medicationCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes with medicine contributed to fall", "Yes without medicine contributed to fall", "No ", "Unknown" }));
        add(medicationCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 366, 284, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Prior to the fall, was a fall risk assessment documented?");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 245, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("At time of the fall, was the patient on medication known to increase the risk of fall?");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 368, -1, -1));

        assessCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        assessCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes with increase in risk for fall", "Yes but with no increase in risk for fall", "No ", "Unknown" }));
        add(assessCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 243, 285, -1));

        contributeCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        contributeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes ", "No ", "Unknown" }));
        add(contributeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 405, 284, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Prior to the fall, what was the patient doing or trying to do?");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 201, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Did restraints, bedrails, or other physical device contribute to the fall?");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 407, -1, -1));

        priorCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        priorCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ambulating without assistance and without an assistive device or medical equipment ", "Ambulating with assistance and/or with an assistive device or medical equipment ", "Changing position (e.g., in bed, chair) ", "Dressing or undressing ", "Navigating bedrails ", "Reaching for an item ", "Showering or bathing ", "Toileting ", "Transferring to or from bed, chair, wheelchair, etc. ", "Undergoing a diagnostic or therapeutic procedure ", "Unknown" }));
        add(priorCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 199, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fall Event");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 29, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Did the patient sustain a physical injury as a result of the fall?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 162, -1, -1));

        injuryCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        injuryCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes-Dislocation ", "Yes-Fracture ", "Yes-Intracranial injury ", "Yes-Laceration requiring sutures ", "Yes-Skin tear, avulsion, hematoma or significant bruising", "No ", "Unknown " }));
        add(injuryCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 160, -1, -1));

        assistedCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        assistedCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Unassisted ", "Assisted ", "Unknown " }));
        add(assistedCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 82, 286, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Was the fall unassisted or assisted?");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 84, -1, -1));

        observedCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        observedCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes - by Staff", "Yes - Visitor, family, or another patient", "No ", "Unknown " }));
        add(observedCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 121, 286, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Was the fall observed?");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 123, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        mainJPanel.remove(this);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.previous(mainJPanel);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void approveBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtn1ActionPerformed
        // TODO add your handling code here:
        fe.setContribute(contributeCB.getSelectedItem().toString());
        fe.setIsAssisted(assistedCB.getSelectedItem().toString());
        fe.setIsInjury(injuryCB.getSelectedItem().toString());
        fe.setIsObserved(observedCB.getSelectedItem().toString());
        fe.setIsRiskAssessed(assessCB.getSelectedItem().toString());
        fe.setRiskFactor(factorCB.getSelectedItem().toString());
        fe.setPriorWork(priorCB.getSelectedItem().toString());
        fe.setPreventive(preventCB.getSelectedItem().toString());
        fe.setOnMedication(medicationCB.getSelectedItem().toString());
        JOptionPane.showMessageDialog(this, "Event Updated Successfully.");
        approveBtn1.setEnabled(false);
    }//GEN-LAST:event_approveBtn1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton approveBtn1;
    private javax.swing.JComboBox assessCB;
    private javax.swing.JComboBox assistedCB;
    private javax.swing.JComboBox contributeCB;
    private javax.swing.JComboBox factorCB;
    private javax.swing.JComboBox injuryCB;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox medicationCB;
    private javax.swing.JComboBox observedCB;
    private javax.swing.JComboBox preventCB;
    private javax.swing.JComboBox priorCB;
    // End of variables declaration//GEN-END:variables
}
