/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.CityAdmin.ViewNewComplainsPkg;

import View.ComplaintsPkg.*;
import Complaints.Category.BasicComplaint;
import Complaints.Category.PeriNatalEvent;
import HelperPkg.Helper;
import Roles.CityAdmin;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class PerinatalEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PerinatalEventJPanel
     */
    PeriNatalEvent pe;
    JPanel mainJPanel;
    CityAdmin cityAdmin;
    public PerinatalEventJPanel(JPanel mainJPanel,CityAdmin cityAdmin,PeriNatalEvent pe) {
        initComponents();
        this.mainJPanel = mainJPanel;
        this.cityAdmin = cityAdmin;
        this.pe=pe;
        setValues();
        
    }

    public void setValues(){
        HelperPkg.Helper h = new Helper();
        numberFetusTB.setText(pe.getFetus());
        numberLiveTB.setText(pe.getLiveBirth());
        dateOfDeliTB.setText(pe.getDoDelivary());
        weightCB.setText(pe.getWeight());
        eventInvolveCB.setSelectedIndex(h.getIndexForComboBox(pe.getEventInvolve(), eventInvolveCB));
        gestationCB.setSelectedIndex(h.getIndexForComboBox(pe.getGestation(), gestationCB));
        primiparaCB.setSelectedIndex(h.getIndexForComboBox(pe.getPrimipara(), primiparaCB));
        affectedCB.setSelectedIndex(h.getIndexForComboBox(pe.getAffectedMembers(), affectedCB));
        motherCB.setSelectedIndex(h.getIndexForComboBox(pe.getMotherOutcome(), motherCB));
        fetusCB.setSelectedIndex(h.getIndexForComboBox(pe.getFetusOutcome(), fetusCB));
        neonateCB.setSelectedIndex(h.getIndexForComboBox(pe.getNeonateOutcome(), neonateCB));
        inducedCB.setSelectedIndex(h.getIndexForComboBox(pe.getInduced(), inducedCB));
        modeCB.setSelectedIndex(h.getIndexForComboBox(pe.getMode(), modeCB));
        instrmentCB.setSelectedIndex(h.getIndexForComboBox(pe.getInstrument(), instrmentCB));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        approveBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        gestationCB = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        numberFetusTB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        primiparaCB = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        motherCB = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        affectedCB = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fetusCB = new javax.swing.JComboBox();
        dateOfDeliTB = new javax.swing.JTextField();
        instrmentCB = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        neonateCB = new javax.swing.JComboBox();
        modeCB = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numberLiveTB = new javax.swing.JTextField();
        eventInvolveCB = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        weightCB = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        inducedCB = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 510, -1, -1));

        approveBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        approveBtn.setText("Update");
        approveBtn.setPreferredSize(new java.awt.Dimension(150, 50));
        approveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                approveBtnActionPerformed(evt);
            }
        });
        add(approveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Was the mother a primipara?");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 149, -1, -1));

        gestationCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20-< 36 weeks ", "36-< 38 weeks ", "38-< 42 weeks ", "42 weeks or more ", "Unknown " }));
        add(gestationCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 76, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("what was the best estimate of  completed weeks of gestation?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 77, -1, -1));
        add(numberFetusTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 186, 401, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Who was affected by the event?");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 224, -1, -1));

        primiparaCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes ", "No ", "Unknown " }));
        add(primiparaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 148, 401, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("How many fetuses were in this pregnancy?");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 187, -1, -1));

        motherCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hemorrhage requiring transfusion ", "Eclampsia ", "Magnesium toxicity ", "Infection - Chorioamnionitis", "Infection - Endometritis", "Infection - Other", "Injury to body-  Uterine rupture", "Injury to body- Third- or fourth-degree perineal laceration", "Injury to body- Ureter", "Injury to body- Bladder", "Injury to body- Bowel", "Injury to body- Other", "Death", "Other", "None" }));
        add(motherCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 262, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Which adverse outcome did the fetus sustain?");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 301, -1, -1));

        affectedCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mother ", "Fetus(es) ", "Neonate(s) " }));
        add(affectedCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 224, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Which adverse outcome(s) did the mother sustain?");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 263, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Which adverse outcome(s) did the neonate sustain?");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 339, -1, -1));

        fetusCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Unexpected death ", "Injury", "None", " " }));
        add(fetusCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 300, 304, -1));
        add(dateOfDeliTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(626, 224, 97, -1));

        instrmentCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes - Vacuum", "Yes- Forceps", "Yes- Vacuum followed by forceps", "No ", "Unknown" }));
        add(instrmentCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 483, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Was instrumentation used to assist vaginal (or attempted vaginal) delivery?  ");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 484, -1, -1));

        neonateCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Birth trauma/injury - Subdural or cerebral hemorrhage", "Birth trauma/injury - Injury to brachial plexus", "Birth trauma/injury - Other", "Five-minute Apgar < 7 and birthweight > 2500 grams ", "Anoxic or hypoxic encephalopathy ", "Seizure(s) ", "Infection (e.g., group B strep) ", "Unexpected death ", "Other", "None" }));
        add(neonateCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 338, 304, -1));

        modeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vaginal delivery ", "Attempted vaginal delivery followed by Cesarean section ", "Cesarean section ", "Unknown " }));
        add(modeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 445, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Number of live births:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 370, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Perinatal Event");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 11, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("What was the date of delivery?");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 225, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Which of the following did the event involve?");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 115, -1, -1));
        add(numberLiveTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 369, 73, -1));

        eventInvolveCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Birthing process (labor and delivery) ", "Intrauterine procedure (prenatal) ", "Other ", "Unknown " }));
        add(eventInvolveCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 114, 393, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("What was the neonate’s birthweight ?");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Immediately prior to delivery, or at the time of the intrauterine procedure (prenatal),");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 54, -1, -1));
        add(weightCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 369, 79, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Was labor induced or augmented?");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 408, -1, -1));

        inducedCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes- Induced ", "Yes- Augmented", "No ", "Unknown " }));
        add(inducedCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 407, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("What was the mode of delivery? ");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 446, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        mainJPanel.remove(this);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.previous(mainJPanel);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void approveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_approveBtnActionPerformed
        // TODO add your handling code here:
        pe.setAffectedMembers(affectedCB.getSelectedItem().toString());
        pe.setDoDelivary(dateOfDeliTB.getText());
        pe.setEventInvolve(eventInvolveCB.getSelectedItem().toString());
        pe.setFetus(numberFetusTB.getText());
        pe.setFetusOutcome(fetusCB.getSelectedItem().toString());
        pe.setGestation(gestationCB.getSelectedItem().toString());
        pe.setInduced(inducedCB.getSelectedItem().toString());
        pe.setInstrument(instrmentCB.getSelectedItem().toString());
        pe.setLiveBirth(numberLiveTB.getText());
        pe.setMode(modeCB.getSelectedItem().toString());
        pe.setMotherOutcome(motherCB.getSelectedItem().toString());
        pe.setNeonateOutcome(neonateCB.getSelectedItem().toString());
        pe.setPrimipara(primiparaCB.getSelectedItem().toString());
        pe.setWeight(weightCB.getText());
        JOptionPane.showMessageDialog(this, "Event Updated Successfully.");
        approveBtn.setEnabled(false);
    }//GEN-LAST:event_approveBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox affectedCB;
    private javax.swing.JButton approveBtn;
    private javax.swing.JTextField dateOfDeliTB;
    private javax.swing.JComboBox eventInvolveCB;
    private javax.swing.JComboBox fetusCB;
    private javax.swing.JComboBox gestationCB;
    private javax.swing.JComboBox inducedCB;
    private javax.swing.JComboBox instrmentCB;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox modeCB;
    private javax.swing.JComboBox motherCB;
    private javax.swing.JComboBox neonateCB;
    private javax.swing.JTextField numberFetusTB;
    private javax.swing.JTextField numberLiveTB;
    private javax.swing.JComboBox primiparaCB;
    private javax.swing.JTextField weightCB;
    // End of variables declaration//GEN-END:variables
}
