/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.StateAdminPkg;

import HelperPkg.Helper;
import Roles.PersonDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class CreatePersonStateAdmin extends javax.swing.JPanel {

    /**
     * Creates new form CreatePersonStateAdmin
     */
    JPanel mainJPanel;
    PersonDirectory pd;
    public CreatePersonStateAdmin(JPanel mainJPanel, PersonDirectory pd) {
        initComponents();
        this.mainJPanel = mainJPanel;
        this.pd = pd;
        warningLbl.setVisible(false);
    }

    boolean validateFields(){
        HelperPkg.Helper h = new Helper();
        boolean flag =  h.isStringProper(nameTB.getText(), streetAddressTB.getText(),cityTB.getText(), stateTB.getText(),countryTB.getText(),zipTB.getText(), phoneTB.getText(), faxTB.getText(), emailTB.getText())
                && h.isProperLength(phoneTB.getText(), 10) && h.isProperLength(zipTB.getText(), 5); 
        
        return  flag;
    }
    void clearFields(){
        nameTB.setText("");
        streetAddressTB.setText("");
        cityTB.setText("");
        stateTB.setText("");
        countryTB.setText("");
        zipTB.setText("");
        phoneTB.setText("");
        faxTB.setText("");
        emailTB.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        nameTB = new javax.swing.JTextField();
        streetAddressTB = new javax.swing.JTextField();
        cityTB = new javax.swing.JTextField();
        stateTB = new javax.swing.JTextField();
        zipTB = new javax.swing.JTextField();
        phoneTB = new javax.swing.JTextField();
        faxTB = new javax.swing.JTextField();
        emailTB = new javax.swing.JTextField();
        createPersonTB = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        countryTB = new javax.swing.JTextField();
        warningLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Create Person");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 87, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Street Address");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 131, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("City");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 168, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("State");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 211, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ZipCode");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 251, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 294, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Fax");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        nameTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(nameTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 159, -1));

        streetAddressTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(streetAddressTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 159, -1));

        cityTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(cityTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 159, -1));

        stateTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(stateTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 159, -1));

        zipTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(zipTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 248, 85, -1));

        phoneTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(phoneTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 290, 159, -1));

        faxTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(faxTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 159, -1));

        emailTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(emailTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 159, -1));

        createPersonTB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createPersonTB.setText("Create Person");
        createPersonTB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPersonTBActionPerformed(evt);
            }
        });
        add(createPersonTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 430, 150, 50));

        clearBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        clearBtn.setText("Clear ");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });
        add(clearBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 430, 149, 50));

        backBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 430, 150, 50));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Country");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 251, -1, -1));

        countryTB.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        add(countryTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 159, -1));

        warningLbl.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        warningLbl.setForeground(new java.awt.Color(255, 0, 0));
        warningLbl.setText("Enter all Input Properly.");
        add(warningLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 295, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 740, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        mainJPanel.remove(this);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.previous(mainJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        clearFields();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void createPersonTBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPersonTBActionPerformed
        // TODO add your handling code here:
        if(validateFields()){
            warningLbl.setVisible(false);
            pd.createPerson(nameTB.getText(), streetAddressTB.getText(), cityTB.getText(), stateTB.getText(), zipTB.getText(), phoneTB.getText(), faxTB.getText(), emailTB.getText(), countryTB.getText());
            clearFields();
            JOptionPane.showMessageDialog(this, "Person Created Successfully.");
        }
        else{
            warningLbl.setVisible(true);
        }
    }//GEN-LAST:event_createPersonTBActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField cityTB;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField countryTB;
    private javax.swing.JButton createPersonTB;
    private javax.swing.JTextField emailTB;
    private javax.swing.JTextField faxTB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField nameTB;
    private javax.swing.JTextField phoneTB;
    private javax.swing.JTextField stateTB;
    private javax.swing.JTextField streetAddressTB;
    private javax.swing.JLabel warningLbl;
    private javax.swing.JTextField zipTB;
    // End of variables declaration//GEN-END:variables
}
