/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.StateAdminPkg;

import Accounts.StateUA;
import View.CountryAdminPkg.*;
import View.ContinentAdminPkg.*;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class StateAdminWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form StateAdminWorkArea
     */
    JPanel mainJPanel;
    StateUA stateUA;
    public StateAdminWorkArea(JPanel mainJPanel,StateUA stateUA) {
        initComponents();
        this.mainJPanel = mainJPanel;
        this.stateUA = stateUA;
        welcomeLbl.setText("Welcome "+ stateUA.getAdmin().getP().getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createCityAdminbtn = new javax.swing.JButton();
        createPersonBtn = new javax.swing.JButton();
        viewAdminsBtn = new javax.swing.JButton();
        viewPersonsBtn = new javax.swing.JButton();
        welcomeLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(0, 153, 204));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        createCityAdminbtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createCityAdminbtn.setText("Create City Admin");
        createCityAdminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createCityAdminbtnActionPerformed(evt);
            }
        });
        add(createCityAdminbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 172, 200, 52));

        createPersonBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        createPersonBtn.setText("Create Person");
        createPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPersonBtnActionPerformed(evt);
            }
        });
        add(createPersonBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 174, 200, 50));

        viewAdminsBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewAdminsBtn.setText("View Admins");
        viewAdminsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAdminsBtnActionPerformed(evt);
            }
        });
        add(viewAdminsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 242, 200, 50));

        viewPersonsBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        viewPersonsBtn.setText("View Persons");
        viewPersonsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPersonsBtnActionPerformed(evt);
            }
        });
        add(viewPersonsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 242, 200, 50));

        welcomeLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        welcomeLbl.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLbl.setText("Welcome");
        add(welcomeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 33, -1, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, 766, -1));

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 113, 13, 405));
    }// </editor-fold>//GEN-END:initComponents

    private void createPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPersonBtnActionPerformed
        // TODO add your handling code here:
        CreatePersonStateAdmin cp = new CreatePersonStateAdmin(mainJPanel, stateUA.getAdmin().getPd());
        mainJPanel.add("State Admin Create Person", cp);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_createPersonBtnActionPerformed

    private void createCityAdminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createCityAdminbtnActionPerformed
        // TODO add your handling code here:
        CreateCityAdmin cp = new CreateCityAdmin(mainJPanel, stateUA);
        mainJPanel.add("State Admin Create City Admin", cp);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_createCityAdminbtnActionPerformed

    private void viewPersonsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPersonsBtnActionPerformed
        // TODO add your handling code here:
        ViewPersonsStateAdmin cp = new ViewPersonsStateAdmin(mainJPanel, stateUA.getAdmin().getPd());
        mainJPanel.add("State Admin View Person", cp);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_viewPersonsBtnActionPerformed

    private void viewAdminsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAdminsBtnActionPerformed
        // TODO add your handling code here:
        ViewAdminsStateAdmin cp = new ViewAdminsStateAdmin(mainJPanel, stateUA.getAdmin());
        mainJPanel.add("State Admin View Admins", cp);
        CardLayout layout = (CardLayout) mainJPanel.getLayout();
        layout.next(mainJPanel);
    }//GEN-LAST:event_viewAdminsBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createCityAdminbtn;
    private javax.swing.JButton createPersonBtn;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton viewAdminsBtn;
    private javax.swing.JButton viewPersonsBtn;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
