/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ComplaintsPkg;

import Complaints.Category.BasicComplaint;
import Complaints.Category.InfectionEvent;
import Roles.CityAdmin;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class HealthInfectionEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HealthInfectionEventJPanel
     */
    JPanel mainJPanel;
    CityAdmin cityAdmin;
    InfectionEvent he;
    public HealthInfectionEventJPanel(JPanel mainJPanel,CityAdmin cityAdmin,BasicComplaint bc) {
        initComponents();
        this.mainJPanel = mainJPanel;
        this.cityAdmin = cityAdmin;
        
        he = cityAdmin.getComplaint().createInfectionEvent();
        he.setBc(bc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        incubatingCB = new javax.swing.JComboBox();
        personCB = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        describeCB = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        othertypeCB = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        typeCB = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        locationCB = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Which of the following best describes the infection?");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 115, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Was the person who determined the infection to be a healthcare-associated infection (HAI)");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 152, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Was the infection determined to be present or incubating on admission?");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, -1, -1));

        incubatingCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes – infection was determined to be present or incubating on admission", "No – infection developed during this admission ", "Unknown" }));
        add(incubatingCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 75, -1, -1));

        personCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes ", "No ", "Unknown" }));
        add(personCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 174, 327, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText(" a healthcare professional with specific training in infectious disease and/or infection control?");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 175, -1, -1));

        describeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Surgical site infection (SSI)", "Community acquired infection ", "Presumed HAI (other than SSI) " }));
        add(describeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 114, 327, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Which other type of infection?");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 251, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Health Infection Event");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 32, -1, -1));

        othertypeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bone or joint infection ", "Central nervous system infection ", "Cardiovascular system infection ", "Eye, ear, nose, throat, or mouth infection ", "Gastrointestinal system infection – non CDI ", "Lower respiratory tract infection (other than pneumonia) ", "Reproductive tract infection ", "Skin or soft tissue infection ", "Systemic infection" }));
        add(othertypeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 250, 327, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("What type of HAI is being reported?");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 213, -1, -1));

        typeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Primary bloodstream infection (BSI) with CLABSI", "Primary bloodstream infection (BSI) without CLABSI", "Pneumonia with ventilator-associated pneumonia", "Pneumonia without ventilator-associated pneumonia", "Urinary tract infection with catheter-associated", "Urinary tract infection without catheter-associated", "Surgical site infection with Organ/space", "Surgical site infection with Deep incisional primary", "Surgical site infection with Deep incisional secondary", "Surgical site infection with Superficial incisional primary", "Surgical site infection with Superficial incisional secondary", "Surgical site infection Unknown.", "Clostridium difficile infection – gastrointestinal system infection ", "Other type of infection that developed during admission", " ", " ", " ", " ", " ", " ", " ", " ", " ", " ", " " }));
        add(typeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 212, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Location of incidence ?");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 296, -1, -1));

        locationCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Specialty care area", "Intensive care unit, including pediatric ", "Neonatal intensive care unit ", "Other location (e.g., surgical or medical ward) ", "Unknown" }));
        add(locationCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 295, 327, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        he.setDescribe(describeCB.getSelectedItem().toString());
        he.setLocation(locationCB.getSelectedItem().toString());
        he.setOtherType(othertypeCB.getSelectedItem().toString());
        he.setPerson(personCB.getSelectedItem().toString());
        he.setPresentInfection(incubatingCB.getSelectedItem().toString());
        he.setType(typeCB.getSelectedItem().toString());
        jButton1.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Event Reported Successfully.");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox describeCB;
    private javax.swing.JComboBox incubatingCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JComboBox locationCB;
    private javax.swing.JComboBox othertypeCB;
    private javax.swing.JComboBox personCB;
    private javax.swing.JComboBox typeCB;
    // End of variables declaration//GEN-END:variables
}
