/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ComplaintsPkg;

import Complaints.Category.BasicComplaint;
import Complaints.Category.MedicationEvent;
import Roles.CityAdmin;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class MedicalEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicalEventJPanel
     */
    MedicationEvent me;
     JPanel mainJPanel;
    CityAdmin cityAdmin;
    public MedicalEventJPanel(JPanel mainJPanel,CityAdmin cityAdmin,BasicComplaint bc) {
        initComponents();
        this.mainJPanel = mainJPanel;
        this.cityAdmin = cityAdmin;
        
        me = cityAdmin.getComplaint().createMedicationEvent();
        me.setBc(bc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        intendedCB = new javax.swing.JComboBox();
        medicationCB = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        actualCB = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        eventCB = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        actionCB = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        charazterizeCB = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(0, 153, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 381, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("What type of medication/substance was involved?");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 106, -1, -1));

        intendedCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        intendedCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cutaneous, topical application ", "Subcutaneous ", "Ophthalmic ", "Oral, including sublingual or buccal ", "Otic ", "Nasal ", "Inhalation ", "Intravenous ", "Intramuscular ", "Intrathecal ", "Epidural ", "Gastric ", "Rectal ", "Vaginal ", "Unknown" }));
        add(intendedCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 260, -1, -1));

        medicationCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        medicationCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Medications- Prescription", "Medications-Compounded preparations", "Medications-Investigational drugs", "Medications-Unknown", "Biological products-Vaccines ", "Biological products-Other biological products", "Nutritional products-Dietary supplements", "Nutritional products-Vitamins or minerals", "Nutritional products-Enteral nutritional products, including infant formula ", "Nutritional products-Parenteral nutritional products", "Expressed human breast milk", "Medical gases", "Contrast media ", "Radiopharmaceuticals", "Patient food (not suspected in drug-food interactions)", "Drug-drug, drug-food, or adverse drug reaction" }));
        add(medicationCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 104, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("What was the actual route of administration?");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 301, -1, -1));

        actualCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        actualCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cutaneous, topical application ", "Subcutaneous ", "Ophthalmic ", "Oral, including sublingual or buccal ", "Otic ", "Nasal ", "Inhalation ", "Intravenous ", "Intramuscular ", "Intrathecal ", "Epidural ", "Gastric ", "Rectal ", "Vaginal ", "Unknown" }));
        add(actualCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 299, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Medicationl Event");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 61, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("What was the intended route of administration?  ");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 262, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("At what stage in the process did the event originate? ");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 223, -1, -1));

        eventCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        eventCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Purchasing ", "Storing ", "Prescribing/ordering ", "Transcribing ", "Preparing", "Dispensing ", "Administering ", "Monitoring ", "Unknown" }));
        add(eventCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(342, 221, 214, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("What was the incorrect action?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 184, -1, -1));

        actionCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        actionCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Incorrect patient ", "Incorrect medication/substance ", "Incorrect dose(s)- Overdose", "Incorrect dose(s)- Underdose", "Incorrect dose(s)- Missed or omitted dose", "Incorrect dose(s)- Extra dose", "Incorrect dose(s)- Unknown", "Incorrect route of administration ", "Incorrect timing- Too early", "Incorrect timing- Too late", "Incorrect timing- Unknown", "Incorrect rate - Too quickly", "Incorrect rate - Too slowly", "Incorrect rate - Unknown", "Incorrect duration of administration or course of therapy ", "Incorrect dosage form ", "Incorrect strength or concentration- Too high", "Incorrect strength or concentration- Too low", "Incorrect strength or concentration- Unknown", "Incorrect preparation", "Expired or deteriorated medication/substance", "Medication/substance that is known to be an allergen to the patient", "Medication/substance that is known to be contraindicated for the patient", "Incorrect patient/family action (e.g., self-administration error) " }));
        add(actionCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 182, 413, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Which of the following best characterizes the event?");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 145, -1, -1));

        charazterizeCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        charazterizeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Incorrect action (process failure or error)  ", "Unsafe condition ", "Adverse reaction in patient to the administered substance", "Unknown" }));
        add(charazterizeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(341, 143, 413, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        me.setAction(actionCB.getSelectedItem().toString());
        me.setActualRoute(actualCB.getSelectedItem().toString());
        me.setCharacterize(charazterizeCB.getSelectedItem().toString());
        me.setIntendedRoute(intendedCB.getSelectedItem().toString());
        me.setOriginated(eventCB.getSelectedItem().toString());
        me.setSubstance(medicationCB.getSelectedItem().toString());
        jButton1.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Event Reported Successfully.");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox actionCB;
    private javax.swing.JComboBox actualCB;
    private javax.swing.JComboBox charazterizeCB;
    private javax.swing.JComboBox eventCB;
    private javax.swing.JComboBox intendedCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JComboBox medicationCB;
    // End of variables declaration//GEN-END:variables
}
