/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ComplaintsPkg;

import Complaints.Category.BasicComplaint;
import Complaints.Category.PeriNatalEvent;
import Roles.CityAdmin;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class PerinatalEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PerinatalEventJPanel
     */
    PeriNatalEvent pe;
    JPanel mainJPanel;
    CityAdmin cityAdmin;
    public PerinatalEventJPanel(JPanel mainJPanel,CityAdmin cityAdmin,BasicComplaint bc) {
        initComponents();
        this.mainJPanel = mainJPanel;
        this.cityAdmin = cityAdmin;
        
        pe = cityAdmin.getComplaint().createPeriNatalEvent();
        pe.setBc(bc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        gestationCB = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        numberFetusTB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        primiparaCB = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        motherCB = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        affectedCB = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fetusCB = new javax.swing.JComboBox();
        instrmentCB = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        neonateCB = new javax.swing.JComboBox();
        modeCB = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numberLiveTB = new javax.swing.JTextField();
        eventInvolveCB = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        weightCB = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        inducedCB = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        discDateCB = new javax.swing.JComboBox();
        discMonthCB = new javax.swing.JComboBox();
        discYearCB = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(0, 153, 204));
        setPreferredSize(new java.awt.Dimension(150, 50));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 463, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Was the mother a primipara?");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 167, -1, -1));

        gestationCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20-< 36 weeks ", "36-< 38 weeks ", "38-< 42 weeks ", "42 weeks or more ", "Unknown " }));
        add(gestationCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(472, 94, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("what was the best estimate of  completed weeks of gestation?");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 95, -1, -1));
        add(numberFetusTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 204, 401, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Who was affected by the event?");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 242, -1, -1));

        primiparaCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes ", "No ", "Unknown " }));
        add(primiparaCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 166, 401, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("How many fetuses were in this pregnancy?");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, -1, -1));

        motherCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Hemorrhage requiring transfusion ", "Eclampsia ", "Magnesium toxicity ", "Infection - Chorioamnionitis", "Infection - Endometritis", "Infection - Other", "Injury to body-  Uterine rupture", "Injury to body- Third- or fourth-degree perineal laceration", "Injury to body- Ureter", "Injury to body- Bladder", "Injury to body- Bowel", "Injury to body- Other", "Death", "Other", "None" }));
        add(motherCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 280, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Which adverse outcome did the fetus sustain?");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 319, -1, -1));

        affectedCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mother ", "Fetus(es) ", "Neonate(s) " }));
        add(affectedCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 242, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Which adverse outcome(s) did the mother sustain?");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 281, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Which adverse outcome(s) did the neonate sustain?");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 357, -1, -1));

        fetusCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Unexpected death ", "Injury", "None", " " }));
        add(fetusCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 318, 304, -1));

        instrmentCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes - Vacuum", "Yes- Forceps", "Yes- Vacuum followed by forceps", "No ", "Unknown" }));
        add(instrmentCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 504, -1, -1));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Was instrumentation used to assist vaginal (or attempted vaginal) delivery?  ");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 505, -1, -1));

        neonateCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Birth trauma/injury - Subdural or cerebral hemorrhage", "Birth trauma/injury - Injury to brachial plexus", "Birth trauma/injury - Other", "Five-minute Apgar < 7 and birthweight > 2500 grams ", "Anoxic or hypoxic encephalopathy ", "Seizure(s) ", "Infection (e.g., group B strep) ", "Unexpected death ", "Other", "None" }));
        add(neonateCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 356, 304, -1));

        modeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vaginal delivery ", "Attempted vaginal delivery followed by Cesarean section ", "Cesarean section ", "Unknown " }));
        add(modeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 464, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Number of live births:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 388, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Perinatal Event");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 29, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("What was the date of delivery?");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 243, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Which of the following did the event involve?");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 133, -1, -1));
        add(numberLiveTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 387, 73, -1));

        eventInvolveCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Birthing process (labor and delivery) ", "Intrauterine procedure (prenatal) ", "Other ", "Unknown " }));
        add(eventInvolveCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 132, 393, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("What was the neonate’s birthweight ?");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(405, 388, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Immediately prior to delivery, or at the time of the intrauterine procedure (prenatal),");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 72, -1, -1));
        add(weightCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 387, 79, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Was labor induced or augmented?");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 426, -1, -1));

        inducedCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes- Induced ", "Yes- Augmented", "No ", "Unknown " }));
        add(inducedCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 425, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("What was the mode of delivery? ");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 465, -1, -1));

        discDateCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        add(discDateCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 242, -1, -1));

        discMonthCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        add(discMonthCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(628, 242, -1, -1));

        discYearCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032" }));
        add(discYearCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(679, 242, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        pe.setAffectedMembers(affectedCB.getSelectedItem().toString());
        pe.setDoDelivary(discDateCB.getSelectedItem().toString() + "/" + discMonthCB.getSelectedItem().toString() + "/" +discYearCB.getSelectedItem().toString());
        pe.setEventInvolve(eventInvolveCB.getSelectedItem().toString());
        pe.setFetus(numberFetusTB.getText());
        pe.setFetusOutcome(fetusCB.getSelectedItem().toString());
        pe.setGestation(gestationCB.getSelectedItem().toString());
        pe.setInduced(inducedCB.getSelectedItem().toString());
        pe.setInstrument(instrmentCB.getSelectedItem().toString());
        pe.setLiveBirth(numberLiveTB.getText());
        pe.setMode(modeCB.getSelectedItem().toString());
        pe.setMotherOutcome(motherCB.getSelectedItem().toString());
        pe.setNeonateOutcome(neonateCB.getSelectedItem().toString());
        pe.setPrimipara(primiparaCB.getSelectedItem().toString());
        pe.setWeight(weightCB.getText());
        jButton1.setEnabled(false);
        JOptionPane.showMessageDialog(this, "Event Reported Successfully.");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox affectedCB;
    private javax.swing.JComboBox discDateCB;
    private javax.swing.JComboBox discMonthCB;
    private javax.swing.JComboBox discYearCB;
    private javax.swing.JComboBox eventInvolveCB;
    private javax.swing.JComboBox fetusCB;
    private javax.swing.JComboBox gestationCB;
    private javax.swing.JComboBox inducedCB;
    private javax.swing.JComboBox instrmentCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox modeCB;
    private javax.swing.JComboBox motherCB;
    private javax.swing.JComboBox neonateCB;
    private javax.swing.JTextField numberFetusTB;
    private javax.swing.JTextField numberLiveTB;
    private javax.swing.JComboBox primiparaCB;
    private javax.swing.JTextField weightCB;
    // End of variables declaration//GEN-END:variables
}
