/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View.ComplaintsPkg;

import Complaints.Category.BasicComplaint;
import Complaints.Category.SurgeryEvent;
import Roles.CityAdmin;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class SurgeryEventJPanel extends javax.swing.JPanel {

    /**
     * Creates new form SurgeryEventJPanel
     */
    SurgeryEvent se;
     JPanel mainJPanel;
    CityAdmin cityAdmin;
    public SurgeryEventJPanel(JPanel mainJPanel,CityAdmin cityAdmin,BasicComplaint bc) {
        initComponents();
        this.mainJPanel = mainJPanel;
        this.cityAdmin = cityAdmin;
        
        se = cityAdmin.getComplaint().createSurgeryEvent();
        se.setBc(bc);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        characterizeAnesCB = new javax.swing.JComboBox();
        characterizeSurgeryCB = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        administratorCB = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        descriptionTB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        discoveredCB = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        specialityCB = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        emergencyCB = new javax.swing.JComboBox();
        eventCB = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        classCB = new javax.swing.JComboBox();
        combinationCB = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        timeCB = new javax.swing.JComboBox();
        complicationCB = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.setPreferredSize(new java.awt.Dimension(150, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 471, -1, -1));

        characterizeAnesCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        characterizeAnesCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dental injury ", "Ocular injury ", "Peripheral nerve injury ", "Awareness (during anesthesia) ", "Malignant hyperthermia", "Problem with anesthetic", "Problem with device used in anesthesia", "Difficulty managing airway", "Other", "None", " ", " ", " ", " " }));
        add(characterizeAnesCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 444, -1, -1));

        characterizeSurgeryCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        characterizeSurgeryCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Surgical site infection ", "Bleeding requiring return to the operating room", "Burn and/or operating room fire", "Incorrect surgical or invasive procedure", "Iatrogenic pneumothorax ", "Unintended laceration or puncture ", "Dehiscence, flap or wound failure or disruption, or graft failure ", "Unintended blockage, obstruction, or ligation ", "Unplanned removal of organ ", "Air embolus ", "Other" }));
        add(characterizeSurgeryCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(373, 412, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("If the event involved anesthesia, which of the following best characterizes the event?");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 446, -1, -1));

        administratorCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        administratorCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anesthesiologist ", "Certified Registered Nurse Anesthetist ", "Other healthcare professional ", "Unknown", "Not Needed" }));
        add(administratorCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 224, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("What was the patient’s documented as a  Physical Classification System  class?");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 84, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Which of the following best characterizes the surgical event?");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 414, -1, -1));
        add(descriptionTB, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 51, 424, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Who administered the anesthesia or sedation?");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 226, -1, -1));

        discoveredCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        discoveredCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Before anesthesia started or, if no anesthesia used, before procedure started ", "After anesthesia started, but before incision or start of procedure ", "After procedure started (incision), but before procedure ended (closure) ", "At closure, if surgical operation ", "After procedure ended, but before patient left operating room or other procedure area ", "During post-anesthesia care/recovery period ", "After post-anesthesia recovery, but before discharge ", "After patient was discharged ", "During anesthesia when no surgical operation or invasive procedure was performed ", "Unknown ", " " }));
        add(discoveredCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 263, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Describe briefly the procedure :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 52, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("When was the event discovered?");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 265, -1, -1));

        specialityCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        specialityCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anesthesiology ", "Cardiology ", "Colorectal surgery ", "Dentistry, including oral surgery ", "Dermatology ", "Emergency medicine ", "Family medicine ", "Gastroenterology ", "General surgery ", "Internal medicine ", "Neurological surgery ", "Obstetrics/Gynecology ", "Ophthalmology ", "Orthopedic surgery ", "Otolaryngology ", "Pediatrics ", "Pediatric surgery ", "Plastic surgery ", "Podiatry ", "Pulmonology ", "Radiology, including vascular and interventional ", "Thoracic surgery ", "Urology ", "Vascular surgery ", "Other" }));
        add(specialityCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 302, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Which combination of anesthesia and sedation was used?");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("What was the specialty of the provider who performed the procedure?");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 304, -1, -1));

        emergencyCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        emergencyCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Yes ", "No ", "Unknown" }));
        add(emergencyCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 114, 227, -1));

        eventCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        eventCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Surgical event", "Anesthesia event", "Major complication associated with surgery/anesthesia" }));
        add(eventCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 341, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Was the procedure performed as an emergency? ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("What best describes the event?");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 343, -1, -1));

        classCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        classCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Class 1 ", "Class 2 ", "Class 3", "Class 4 ", "Class 5 ", "ASA classification was not documented" }));
        add(classCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 82, -1, -1));

        combinationCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        combinationCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Anesthesia only ", "Anesthesia and sedation", "Sedation only ", "None ", "Unknown", " ", " " }));
        add(combinationCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 146, 227, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Surgery or Anesthesia Event");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 15, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("What was the length of time from induction of anesthesia to the end of anesthesia?");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, -1, -1));

        timeCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        timeCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Less than 1 hour ", "Greater than or equal to 1 hour, but less than 3 hours ", "Greater than or equal to 3 hours, but less than 5 hours ", "Greater than or equal to 5 hours ", "Unknown", "None" }));
        add(timeCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 185, -1, -1));

        complicationCB.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        complicationCB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cardiac or circulatory event ", "Central nervous system event ", "Renal failure, impairment, or insufficiency ", "Respiratory failure", "Other" }));
        add(complicationCB, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 380, 274, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Which of the following major complications occurred?");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 382, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        se.setAdministor(administratorCB.getSelectedItem().toString());
        se.setAnesthesia(combinationCB.getSelectedItem().toString());
        se.setAnestheticEvent(characterizeAnesCB.getSelectedItem().toString());
        se.setComplication(complicationCB.getSelectedItem().toString());
        se.setDecription(descriptionTB.getText());
        se.setEventDiscovery(discoveredCB.getSelectedItem().toString());
        se.setEventType(eventCB.getSelectedItem().toString());
        se.setIsEmergency(emergencyCB.getSelectedItem().toString());
        se.setPatientClass(classCB.getSelectedItem().toString());
        se.setSpeciality(specialityCB.getSelectedItem().toString());
        se.setSurguryCharac(characterizeSurgeryCB.getSelectedItem().toString());
        se.setTime(timeCB.getSelectedItem().toString());
        jButton1.setEnabled(false);
          JOptionPane.showMessageDialog(this, "Event Reported Successfully.");
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox administratorCB;
    private javax.swing.JComboBox characterizeAnesCB;
    private javax.swing.JComboBox characterizeSurgeryCB;
    private javax.swing.JComboBox classCB;
    private javax.swing.JComboBox combinationCB;
    private javax.swing.JComboBox complicationCB;
    private javax.swing.JTextField descriptionTB;
    private javax.swing.JComboBox discoveredCB;
    private javax.swing.JComboBox emergencyCB;
    private javax.swing.JComboBox eventCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox specialityCB;
    private javax.swing.JComboBox timeCB;
    // End of variables declaration//GEN-END:variables
}
